[package]
name = "shared"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-multiplatform/Base-Project-Template.git"

[features]
default = ["all-tests"]
ui-tests = []
all-tests = ["ui-tests"]

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
graphical_engine = { path = "./Graphical-Engine-Library/" }
log = "0.4"
env_logger = "0.10"
winit = "0.28"
vulkano = "0.33"
vulkano-win = "0.33"
