[package]
name = "shared"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-multiplatform/Base-Project-Template.git"

[features]
default = ["all-tests"]
ui-tests = []
all-tests = ["ui-tests"]

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
<<<<<<< HEAD
graphical_engine = { path = "./Graphical-Engine-Library/" }
log = "0.4.14"
env_logger = "0.10.0"
winit = "0.27.0"
vulkano = "0.31.0"
vulkano-win = "0.31.0"
=======
winit = "0.28"

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.28", features = ["android-native-activity"] }
>>>>>>> upstream/main
