name: Upstream Merger

on:
  push:
    branches: ["main"]

jobs:
  upstream_merger:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        repository: [rust-multiplatform/Graphical-Engine-Example-Basic-Triangle]

    steps:
      - name: Merge upstream
        run: |
          echo ">>> ${{ matrix.repository }}"

          echo "> Setting git ..."
          git config --global user.name "GitHub CI"
          git config --global user.email "dev@sakul-flee.de"
          git config --global pull.rebase false
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key
          chmod 0700 ~/.ssh
          chmod 0600 ~/.ssh/key
          eval `ssh-agent -s`
          ssh-add ~/.ssh/key
          
          echo "> Clone repository"
          git clone --recursive git@github.com:${{ matrix.repository }} ${{ matrix.repository }}
          cd '${{ matrix.repository }}'
          git checkout main
          git pull origin main
          
          echo "> Adding upstream"
          git remote add upstream https://github.com/rust-multiplatform/Base-Project-Template

          echo "> Fetching ..."
          git fetch --all

          echo "> Merging ..."
          git merge -s theirs upstream/main origin/main

          echo "> Pushing ..."
          git add --all || true
          git commit -m "Upstream merge ($(date +%d.%m.%Y_%H:%M:%S))" || true
          git push origin main